#ifndef TURAG_CONSOLE_UTIL_VIRTUALFELDBUSDEVICE_CONFIG_TINA_H
#define TURAG_CONSOLE_UTIL_VIRTUALFELDBUSDEVICE_CONFIG_TINA_H


#define TURAG_CRC_CRC8_ALGORITHM 			1
#define TURAG_CRC_INLINED_CALCULATION 		1


#endif // TURAG_CONSOLE_UTIL_VIRTUALFELDBUSDEVICE_CONFIG_TINA_H
